### ISSUE TITLE
Ensure we have issues on file for tracking utility crates for all Web platform features

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/gloo#41]
Would be A++++ if someone went through https://platform.html5.org/ and made sure we had an associated tracking issue for each item there (where it makes sense). Lots of potential utility crates!

**Comment by yoshuawuyts** [comment]
@fitzgen is there a good example of such an issue already that we could use as a template for filing these tracking issues?

**Comment by rylev** [comment]
It seems like that the existing issues that fit in this category are quite simple: https://github.com/rustwasm/gloo/issues/6#issue-414841275 Perhaps we should just create them, and more information can be added later.

**Comment by fitzgen** [comment]
We don't have a template yet, but creating one would be awesome!

I think most of this would be "mid-level" APIs at least initially, and the big questions to resolve with these crates are:

* [ ] What would a direct Rust translation (e.g. a `callback`-based) API look like?
* [ ] Does it make sense to add a `Future`- and/or `Stream`-based API on top of that?
* [ ] Are there existing, cross-platform crates that are widely used in the ecosystem that we should consider integration with?

**Comment by derekdreery** [comment]
I'm going to knock this work out now.

**Comment by derekdreery** [comment]
List generated by [scraping platform.html5.org](https://github.com/derekdreery/web_api_scraper).

# Core platform
  - [HTML](https://html.spec.whatwg.org/multipage/)
  - [DOM](https://dom.spec.whatwg.org/)
  - [ECMAScript](https://tc39.github.io/ecma262/)
  - [WebAssembly](https://webassembly.github.io/spec/)
  - [URL](https://url.spec.whatwg.org/)
  - [Fetch (includes CORS)](https://fetch.spec.whatwg.org/)
  - [XMLHttpRequest](https://xhr.spec.whatwg.org/)
  - [Encoding](https://encoding.spec.whatwg.org/)

# CSS features
  - [CSS roadmap](http://www.w3.org/Style/CSS/current-work#roadmap)
  - [Animations](https://drafts.csswg.org/css-animations/)
  - [Background-image options](https://drafts.csswg.org/css-backgrounds/#backgrounds)
  - [Border images](https://drafts.csswg.org/css-backgrounds/#the-border-image)
  - [Border radius (rounded corners)](https://drafts.csswg.org/css-backgrounds/#the-border-radius)
  - [Box shadows](https://drafts.csswg.org/css-backgrounds/#box-shadow)
  - [Box sizing](https://drafts.csswg.org/css-ui/#box-sizing)
  - [Cascading and inheritance](https://drafts.csswg.org/css-cascade/)
  - [Colors](https://drafts.csswg.org/css-color/)
  - [Compositing and Blending](https://drafts.fxtf.org/compositing/)
  - [Containment](https://drafts.csswg.org/css-contain/)
  - [Device Adaptation](https://drafts.csswg.org/css-device-adapt/)
  - [Downloadable fonts (@font-face)](https://drafts.csswg.org/css-fonts/)
  - [Exclusions](https://drafts.csswg.org/css-exclusions/)
  - [Feature queries (@supports)](https://drafts.csswg.org/css-conditional/#at-supports)
  - [Filter Effects](https://drafts.fxtf.org/filters/)
  - [Fixed positioning (position:fixed)](http://www.w3.org/TR/CSS21/visuren.html#fixed-positioning)
  - [Flexible box layout (Flexbox)](https://drafts.csswg.org/css-flexbox/)
  - [Font-feature settings](https://drafts.csswg.org/css-fonts/#font-rend-props)
  - [Font loading](https://drafts.csswg.org/css-font-loading/)
  - [Gradients](https://drafts.csswg.org/css-images/)
  - [Grid layout](https://drafts.csswg.org/css-grid/)
  - [Hyphenation](https://drafts.csswg.org/css-text/#hyphenation)
  - [Image Values and Replaced Content](https://drafts.csswg.org/css-images/)
  - [Logical properties](https://drafts.csswg.org/css-logical-props/)
  - [Masking](https://drafts.fxtf.org/css-masking/)
  - [Media Queries](https://drafts.csswg.org/mediaqueries/)
  - [Motion paths](https://drafts.fxtf.org/motion/)
  - [Multiple-column layout](https://drafts.csswg.org/css-multicol/)
  - [Multiple backgrounds](https://drafts.csswg.org/css-backgrounds/)
  - [Opacity](https://drafts.csswg.org/css-color/#transparency)
  - [Overflow](https://drafts.csswg.org/css-overflow/)
  - [Pointer events](https://wiki.csswg.org/spec/css4-ui#pointer-events)
  - [Pseudo-elements](https://drafts.csswg.org/css-pseudo/)
  - [Scroll Snap Points](https://drafts.csswg.org/css-snappoints/)
  - [Selectors](https://drafts.csswg.org/selectors/)
  - [Shapes](https://drafts.csswg.org/css-shapes/)
  - [Sticky positioning (position:sticky)](https://drafts.csswg.org/css-position/#sticky-pos)
  - [Style attributes](https://drafts.csswg.org/css-style-attr/)
  - [Syntax](https://drafts.csswg.org/css-syntax/)
  - [Text decoration](https://drafts.csswg.org/css-text-decor/)
  - [Text overflow](https://drafts.csswg.org/css-ui/#text-overflow)
  - [Text shadows](https://drafts.csswg.org/css-text-decor/#text-shadow-property)
  - [Transforms (2D)](https://drafts.csswg.org/css-transforms/)
  - [Transforms (3D)](https://drafts.csswg.org/css-transforms/)
  - [Transitions](https://drafts.csswg.org/css-transitions/)
  - [Values and Units](https://drafts.csswg.org/css-values/)
  - [Will Change](https://drafts.csswg.org/css-will-change/)
  - [Writing modes](https://drafts.csswg.org/css-writing-modes/)
  - [CSSOM (CSS Object Model)](https://drafts.csswg.org/cssom/)
  - [CSSOM View Module](https://drafts.csswg.org/cssom-view/)

# Graphics and typography
  - [Canvas](https://html.spec.whatwg.org/multipage/scripting.html#the-canvas-element)
  - [WebGL](https://www.khronos.org/registry/webgl/specs/latest/)
  - [SVG](http://www.w3.org/TR/SVG/)
  - [WOFF](http://dev.w3.org/webfonts/WOFF2/spec/)
  - [MathML](http://www.w3.org/TR/MathML/)
  - [Web Animations](https://w3c.github.io/web-animations/)

# Media
  - [Web Audio API](https://webaudio.github.io/web-audio-api/)
  - [WebVTT](http://dev.w3.org/html5/webvtt/)
  - [Media Source Extensions](https://w3c.github.io/media-source/)
  - [Media Fragments](http://www.w3.org/TR/media-frags/)

# Platform interaction, events, messaging
  - [Notifications API](https://notifications.spec.whatwg.org/)
  - [Cross-document messaging](https://html.spec.whatwg.org/multipage/comms.html#web-messaging)
  - [Channel messaging](https://html.spec.whatwg.org/multipage/comms.html#channel-messaging)
  - [Fullscreen API](https://fullscreen.spec.whatwg.org/)
  - [Geolocation](http://dev.w3.org/geo/api/spec-source.html)
  - [Device Orientation](https://w3c.github.io/deviceorientation/spec-source-orientation.html)
  - [Screen Orientation](https://w3c.github.io/screen-orientation/)
  - [UI Events (formerly DOM Events)](https://w3c.github.io/uievents/)
  - [Pointer Events](https://w3c.github.io/pointerevents/)
  - [Touch Events](http://www.w3.org/TR/touch-events/)
  - [Pointer Lock](https://w3c.github.io/pointerlock/)
  - [Gamepad](https://w3c.github.io/gamepad/)
  - [getUserMedia](https://w3c.github.io/mediacapture-main/getusermedia.html)
  - [Battery Status](https://w3c.github.io/battery/)
  - [Vibration](http://dev.w3.org/2009/dap/vibration/)
  - [Beacon](https://w3c.github.io/beacon/)
  - [HTML Media Capture (the capture attribute)](http://dev.w3.org/2009/dap/camera/)
  - [Clipboard API and events](https://w3c.github.io/clipboard-apis/)

# Storage and Files
  - [Storage](https://storage.spec.whatwg.org/)
  - [Web Storage](https://html.spec.whatwg.org/multipage/webstorage.html#webstorage)
  - [Indexed Database](https://w3c.github.io/IndexedDB/)
  - [File API](https://w3c.github.io/FileAPI/)
  - [Blob URLs](https://w3c.github.io/FileAPI/#url)
  - [File Reader](https://w3c.github.io/FileAPI/#dfn-filereader)
  - [File and Directory Entries API](https://wicg.github.io/entries-api/)

# Real-time communication
  - [WebRTC](https://w3c.github.io/webrtc-pc/)
  - [WebSocket protocol](https://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol)
  - [WebSocket API](https://html.spec.whatwg.org/multipage/comms.html#network)
  - [Server-Sent Events](https://html.spec.whatwg.org/multipage/comms.html#server-sent-events)
  - [Push API](https://w3c.github.io/push-api/)

# Web Components
  - [Custom Elements](http://html.spec.whatwg.org/multipage/#custom-elements)
  - [Shadow DOM](https://dom.spec.whatwg.org/#shadow-trees)
  - [Templates](https://html.spec.whatwg.org/multipage/scripting.html#the-template-element)

# HTML bonus features
  - [classList (DOMTokenList)](https://dom.spec.whatwg.org/#dom-element-classlist)
  - [dataset (data-* attributes)](https://html.spec.whatwg.org/multipage/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes)
  - [async for scripts](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-async)
  - [defer for scripts](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-defer)
  - [Session-history management](https://html.spec.whatwg.org/multipage/browsers.html#history)
  - [hashchange](https://html.spec.whatwg.org/multipage/browsers.html#hashchangeevent)
  - [Sandboxed iframe](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-iframe-sandbox)
  - [Drag and drop](https://html.spec.whatwg.org/multipage/interaction.html#dnd)
  - [contentEditable](https://html.spec.whatwg.org/multipage/interaction.html#attr-contenteditable)
  - [ARIA](http://www.w3.org/TR/wai-aria/)

# Performance optimization and analysis
  - [Web Workers](https://html.spec.whatwg.org/multipage/workers.html#workers)
  - [Shared Workers](https://html.spec.whatwg.org/multipage/workers.html#shared-workers)
  - [Timing control for script-based animations](https://html.spec.whatwg.org/multipage/webappapis.html#animation-frames)
  - [Navigation Timing](http://www.w3.org/TR/navigation-timing/)
  - [Page Visibility](http://www.w3.org/TR/page-visibility/)
  - [User Timing](http://www.w3.org/TR/user-timing/)
  - [Performance Timeline](http://www.w3.org/TR/performance-timeline/)
  - [High Resolution Time](http://www.w3.org/TR/hr-time/)
  - [SIMD (Single instruction, multiple data)](https://tc39.github.io/ecmascript_simd/)

# Security and privacy
  - [Content Security Policy (CSP)](https://w3c.github.io/webappsec/specs/content-security-policy/)
  - [Upgrade Insecure Requests](https://w3c.github.io/webappsec/specs/upgrade/)
  - [Web Cryptography API](https://w3c.github.io/webcrypto/Overview.html)
  - [Referrer policy](https://w3c.github.io/webappsec/specs/referrer-policy/)
  - [Tracking Preference Expression (DNT)](http://www.w3.org/2011/tracking-protection/drafts/tracking-dnt.html)
  - [Web Authentication](https://w3c.github.io/webauthn)

# Other core-platform bonus features
  - [Structured cloning](https://html.spec.whatwg.org/multipage/infrastructure.html#safe-passing-of-structured-data)
  - [Transferable objects](https://html.spec.whatwg.org/multipage/infrastructure.html#transferable-objects)
  - [Mutation observers](https://dom.spec.whatwg.org/#mutation-observers)
  - [Streams](https://streams.spec.whatwg.org/)
  - [DOM Parsing and Serialization](https://w3c.github.io/DOM-Parsing/)
  - [DOM XPath](https://wiki.whatwg.org/wiki/DOM_XPath)
  - [Quirks Mode](https://quirks.spec.whatwg.org/)
  - [Internationalization API](https://tc39.github.io/ecma402/)
  - [Promises](https://tc39.github.io/ecma262/#sec-promise-objects)
  - [JSON parsing](https://tc39.github.io/ecma262/#sec-json.parse)
  - [Typed Array](https://tc39.github.io/ecma262/#sec-typedarray-objects)
  - [Service Workers](https://w3c.github.io/ServiceWorker/)
  - [Intersection Observer](https://w3c.github.io/IntersectionObserver/)
  - [querySelector()  method](https://dom.spec.whatwg.org/#dom-parentnode-queryselector)
  - [matches()  method](https://dom.spec.whatwg.org/#dom-element-matches)
  - [matchMedia()  method](https://drafts.csswg.org/cssom-view/#dom-window-matchmedia)
  - [data URLs](https://tools.ietf.org/html/rfc2397)

# Foundations
  - [HTTP](https://tools.ietf.org/wg/httpbis/)
  - [HTTP/2](https://tools.ietf.org/html/draft-ietf-httpbis-http2/)
  - [TLS](https://tools.ietf.org/html/rfc2818)
  - [Cookies](https://tools.ietf.org/html/rfc6265)
  - [Origin](https://tools.ietf.org/html/rfc6454)
  - [Unicode](http://www.unicode.org/versions/latest/)
  - [MIME Sniffing](https://mimesniff.spec.whatwg.org/)

**Comment by derekdreery** [comment]
Some of these items are not really APIs, for example the CSS roadmap, and others are very niche and probably not often used. Would it be better to create tracking issues for all items, or do it on an ad-hoc basis?

**Comment by yoshuawuyts** [comment]
@derekdreery oh that's really good; nice work! What we did for async-std was create dedicated tracking issues; for example [streams](https://github.com/async-rs/async-std/issues/129). 

I think creating a tracking issue per-heading would probably work well; then gathering each tracking issue under a shared milestone to track overall progress.

Something we also found worked well was regularly announce these issues on ["This week in rust: call for participation"](https://users.rust-lang.org/t/twir-call-for-participation/4821). With a little bit of outreach it's probably possible to knock a lot of these out in no-time.

**Comment by Pauan** [comment]
@derekdreery Thanks! I think it would be best to create issues on an ad-hoc basis, so we can ignore things which don't make sense for gloo.
